[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
oct-cloud = { path = "crates/oct-cloud" }

assert_cmd = "2.0.16"
async-trait = "0.1.85"
aws-config = "1.5.14"
aws-sdk-ec2 = "1.101.0"
aws-sdk-ecr = "1.51.0"
aws-sdk-iam = "1.57.0"
axum = "0.8.1"
base64 = "0.22.1"
clap = { version = "4.5.26", features = ["derive"] }
predicates = "3.1.3"
serde = "1.0.217"
serde_derive = "1.0.213"
serde_json = "1.0.137"
tempfile = "3.15.0"
tokio = { version = "1.43.0", features = ["full"] }
mockall = "0.13.1"
mockito = "1.6.1"
uuid = { version = "1.12.0", features = ["v4"] }
log = "0.4.25"
env_logger = "0.11.6"
toml = "0.8.19"
reqwest = { version = "0.12.12", features = ["json"] }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3" }
grcov = "0.8.20"

[workspace.lints.rust]
unsafe_code = "warn"
unreachable_pub = "warn"
