[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
ct-cloud = { path = "crates/ct-cloud" }

assert_cmd = "2.0.16"
async-trait = "0.1.83"
aws-config = "1.5.9"
aws-sdk-ec2 = "1.83.0"
clap = { version = "4.5.20", features = ["derive"] }
predicates = "3.1.2"
serde = "1.0.213"
serde_derive = "1.0.213"
serde_json = "1.0.132"
tempfile = "3.13.0"
tokio = { version = "1.41.0", features = ["full"] }
