[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
oct-cloud = { path = "crates/oct-cloud" }

assert_cmd = "2.0.16"
async-trait = "0.1.85"
aws-config = "1.5.13"
aws-sdk-ec2 = "1.101.0"
aws-sdk-ecr = "1.51.0"
aws-sdk-iam = "1.56.0"
axum = "0.8.1"
async-trait = "0.1.83"
aws-config = "1.5.12"
aws-sdk-ec2 = "1.94.0"
aws-sdk-ecr = "1.51.0"
aws-sdk-iam = "1.50.0"
base64 = "0.22.1"
clap = { version = "4.5.23", features = ["derive"] }
predicates = "3.1.3"
serde = "1.0.217"
serde_derive = "1.0.213"
serde_json = "1.0.134"
tempfile = "3.14.0"
tokio = { version = "1.42.0", features = ["full"] }
mockall = "0.13.1"
uuid = { version = "1.11.0", features = ["v4"] }
log = "0.4.22"
env_logger = "0.11.6"
toml = "0.8.19"
reqwest = "0.12.11"
