[package]
name = "oct-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
oct-orchestrator = { workspace = true }

assert_cmd = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
predicates = { workspace = true }
env_logger = { workspace = true }

[lints]
workspace = true
