[project]
name = "python-fastapi"

[[project.services]]
name = "app"
image = "ghcr.io/opencloudtool/example-python-fastapi:latest"
internal_port = 8000
external_port = 8000
cpus = 250
memory = 64

[[project.services]]
name = "app2"
image = "ghcr.io/opencloudtool/example-python-fastapi:latest"
internal_port = 8000
external_port = 8001
cpus = 250
memory = 64
