[package]
name = "oct-cloud"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-ec2 = { workspace = true }
aws-sdk-ecr = { workspace = true }
aws-sdk-iam = { workspace = true }
base64 = { workspace = true }
tokio = { workspace = true, features = ["full"] }
mockall = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { workspace = true, features = ["v4"] }
log = { workspace = true }
env_logger = { workspace = true }
