[package]
name = "oct-ctl"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true}
serde = {  workspace = true, features = ["derive"] }
serde_json = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
