[package]
name = "ct-cloud"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-ec2 = { workspace = true }
tokio = { workspace = true, features = ["full"] }
