name: Post-submit Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

# Add this concurrency configuration
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: ec2
        options: >-
          --name=localstack
          --health-cmd="curl -sS http://localhost:4566/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build
      run: cargo build --verbose

    - name: Run fmt
      run: cargo fmt --check

    - name: Run tests
      env:
        RUST_BACKTRACE: full
        AWS_ENDPOINT_URL: http://localhost:4566
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
      run: cargo test --verbose
