name: Release oct-ctl

on:
  workflow_run:
    workflows:
      - Post-submit Checks
    types:
      - completed
  

env:
  CARGO_TERM_COLOR: always

# Add this concurrency configuration
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref_name == 'main' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build oct-ctl
      run: cargo build -p oct-ctl --release --verbose

    - name: Tip Tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git tag -fa tip -m "Latest Continuous Release"
        git push -f origin tip

    - name: Upload release
      uses: softprops/action-gh-release@v2
      with:
        name: 'oct-ctl Tip'
        prerelease: true
        tag_name: tip
        target_commitish: ${{ github.sha }}
        files: |
          target/release/oct-ctl
