name: Release oct-ctl

on:
  workflow_run:
    workflows:
      - Post-submit Checks
    types:
      - completed
  

env:
  CARGO_TERM_COLOR: always

# Add this concurrency configuration
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref_name == 'main' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build oct-ctl
      run: cargo build -p oct-ctl --release --verbose

    - name: Upload release
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      run: |
        git tag -fa tip -m "Latest Continuous Release"
        git push -f origin tip
        gh release create tip target/release/oct-ctl --title "Latest Continuous Release" --notes "This is the latest build of oct-ctl." --target tip --prerelease --force